server:
  port: 8089
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false


springdoc:
  enable-native-support: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  jpa:
    show-sql: true
  datasource:
    url: ${DB_CONNECTION:jdbc:mysql://localhost:3306/banco?useMysqlMetadata=true&serverTimezone=America/Guayaquil&allowPublicKeyRetrieval=false}
    username: ${DB_USER:pablo}
    password: ${DB_PWD:12qwaszx}
  devtools:
    restart:
      enabled: true

  application:
    name: Banco

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

messages:
  codenotfound: "-1"
  messagenotfoud: "No se encontro información para mostrar"
  codeok: "0"
  messageok: "Operacion ejecutada con éxito"
  codduplicateversion: "-2"
  messageduplicaversion: "Ya existe una version con esa infomación"
  codduplicatestate: "-3"
  messageduplicatestate: "No es posible tener dos versiones habilitadas"
  codnotexistuserterm: "-999"
  messagenotexistuserterm: "No existen registros para modificar"
  codbadaceptedtermcondition: "-4"
  messagebadtermcondition: "No se puede aceptar dos veces la misma version de temrinos y condiciones"
  messagecodeexistpublishitem: "-5"
  messageexistpublishitem: "Existen terminos&condiciones ó piliticas que se ecuentran publicadas"
  healthapp: "1"
  isactiveintegration: "1"
  messagecodeexistcontent: "-6"
  messageexistcontent: "Ya existe un documento con este contenido"




logging:
  level:
    com:
      zaxxer:
        hikari: ERROR
    feign: DEBUG

